SITE_CONFIGS = {
  'TechCrunch': {
    'url': 'https://techcrunch.com/',
    'article_list_xpath': '',
    'title_xpath': '',
    'author_xpath': '',
    'image_xpath': '',
    'article_url_xpath': '',
    'date_xpath': '',
  },
  'Wired': {
    'url': 'https://www.wired.com/',
    'article_list_xpath': '',
    'title_xpath': '',
    'author_xpath': '',
    'image_xpath': '',
    'article_url_xpath': '',
    'date_xpath': '',
  },
  'BusinessInsider': {
    'url': 'https://www.businessinsider.com/tech',
    'article_list_xpath': '',
    'title_xpath': '',
    'author_xpath': '',
    'image_xpath': '',
    'article_url_xpath': '',
    'date_xpath': '',
  },
  'Engadget': {
    'url': 'https://www.engadget.com/',
    'article_list_xpath': '',
    'title_xpath': '',
    'author_xpath': '',
    'image_xpath': '',
    'article_url_xpath': '',
    'date_xpath': '',
  },
  'TheVerge': {
    'url': 'https://www.theverge.com/',
    'article_list_xpath': '',
    'title_xpath': '',
    'author_xpath': '',
    'image_xpath': '',
    'article_url_xpath': '',
    'date_xpath': '',
  },
}